### ISSUE TITLE
Custom build in Mageia 8 fail

### ISSUE THREAD

**Issue by katnatek** [yasoob/youtube-dl-GUI#32]
```
youtube-dl-gui 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Threads/Download.py", line 146, in run
    self.download()
  File "/usr/lib/python3.8/site-packages/Threads/Download.py", line 123, in download
    ydl.download([self.url])
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1970, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 352, in real_download
    return download()
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 301, in download
    self._hook_progress({
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 374, in _hook_progress
    ph(status)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/fragment.py", line 246, in frag_progress_hook
    self._hook_progress(state)
  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 374, in _hook_progress
    ph(status)
  File "/usr/lib/python3.8/site-packages/Threads/Download.py", line 55, in hook
    self.bytes = self.format_bytes(li.get("total_bytes", "unknown"))
  File "/usr/lib/python3.8/site-packages/Threads/Download.py", line 183, in format_bytes
    _bytes = float(_bytes)
ValueError: could not convert string to float: 'unknown'
Abortado (`core' generado)
```

**Comment by katnatek** [comment]
Fixed used system python3-youtube-dl package

**Comment by oleksis** [comment]
@katnatek Thanks 

I will check the conversion of `_bytes` to manager the Exception
